[theme]
primaryColor = "#FF4B4B"
backgroundColor = "#1e4b1e"
secondaryBackgroundColor = "#59bb0e"
textColor = "#77fd09"
font = "sans serif"

[server]
headless = true

# This sets wide mode as default
[browser]
gatherUsageStats = false

# Add this section for wide mode
[client]
showSidebarNavigation = true